---
title: "tut2"
author: "Che-Yu Wang"
format: pdf
editor: visual
---
```{r}
install.packages("usethis")
library(usethis)
create_github_token()
```
```{r} 

install.packages("gitcreds")
library(gitcreds)
gitcreds_set()
```

```{r}
#### Preamble ####
# Purpose: write and read the data on 2021 shelter usage and make table
# Author: Che-Yu Wang
# Email: Cheyu.wang@mail.utoronto.ca or andrewcy0310@gmail.com
# Date: January 15th 2024
# Prerequisites: analysis data shelter from 2021

#### Workspace setup ####
install.packages("opendatatoronto")
install.packages("knitr")
install.packages("janitor")
install.packages("tidyverse")

```



```{r}
library(knitr)
library(janitor)
library(opendatatoronto)
library(tidyverse)
#### Acquire ####
toronto_shelters <-
  # Each package is associated with a unique id  found in the "For 
  # Developers" tab of the relevant page from Open Data Toronto
  # https://open.toronto.ca/dataset/daily-shelter-overnight-service-occupancy-capacity/
  list_package_resources("21c83b32-d5a8-4106-a54f-010dbe49f6f2") |>
  # Within that package, we are interested in the 2021 dataset
  filter(name == 
    "daily-shelter-overnight-service-occupancy-capacity-2021.csv") |>
  # Having reduced the dataset to one row we can get the resource
  get_resource()


```

```{r}
# clean the data from this part to reform the format 
toronto_shelters_clean <-
  clean_names(toronto_shelters) |>
  mutate(occupancy_date = ymd(occupancy_date)) |> 
  select(occupancy_date, occupied_beds)

head(toronto_shelters_clean)

```

```{r}
library(knitr)
toronto_shelters_clean |>
  mutate(occupancy_month = month(
    occupancy_date,
    label = TRUE,
    abbr = FALSE
  )) |>
  arrange(month(occupancy_date)) |> 
  drop_na(occupied_beds) |>
  summarise(number_occupied = mean(occupied_beds),
            .by = occupancy_month) |>
  kable(
    col.names = c("Month", "Average daily number of occupied beds"),
    digits = 1
  )
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)


# Create the bar chart for occupancy month and average occupied beds 
ggplot(monthly_summary, aes(x = occupancy_month, y = average_occupied_beds)) +
  geom_bar(stat = "identity", fill = "yellow") +  
  labs(
    title = "Average Occupied Beds per Month in 2021",
    x = "Month",
    y = "Average Occupied Beds"
  ) +
  theme_minimal()


```
